// <auto-generated />
namespace DrunkenChair.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class raceStartingResources2Perks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(raceStartingResources2Perks));
        
        string IMigrationMetadata.Id
        {
            get { return "201503051415044_raceStartingResources2Perks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
