// <auto-generated />
namespace DrunkenChair.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addSkills2Environments1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addSkills2Environments1));
        
        string IMigrationMetadata.Id
        {
            get { return "201503091631343_addSkills2Environments1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
