// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Niklasson.EonIV.DataAccess.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RenameBackgroundModification_IDtoModificationContainerId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameBackgroundModification_IDtoModificationContainerId));
        
        string IMigrationMetadata.Id
        {
            get { return "201508261301573_RenameBackgroundModification_IDtoModificationContainerId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
